### ISSUE TITLE
Conda package should depend on maven

### ISSUE THREAD

**Issue by pgunn** [saalfeldlab/paintera#231]
maven is available in conda - if you make the conda package depend on it that's one less thing for conda users to install.

**Comment by hanslovsky** [comment]
Unfortunately, maven on conda(-forge) depends on OpenJDK:
```sh
conda search -c conda-forge maven=3.6.0 --info
Loading channels: done
maven 3.6.0 0
-------------
file name   : maven-3.6.0-0.tar.bz2
name        : maven
version     : 3.6.0
build       : 0
build number: 0
size        : 8.6 MB
license     : Apachev2
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/maven-3.6.0-0.tar.bz2
md5         : 8bc874b816368bcc4f79d62e2d3769ef
timestamp   : 2018-12-08 02:53:59 UTC
dependencies: 
  - openjdk


maven 3.6.0 0
-------------
file name   : maven-3.6.0-0.tar.bz2
name        : maven
version     : 3.6.0
build       : 0
build number: 0
size        : 8.6 MB
license     : Apachev2
subdir      : linux-64
url         : https://repo.anaconda.com/pkgs/main/linux-64/maven-3.6.0-0.tar.bz2
md5         : 8e767e01fe71eb338938a90cbbfec2f6
timestamp   : 2018-11-13 04:07:40 UTC
dependencies: 
  - openjdk
```
OpenJDK [does not ship with JavaFX on conda](https://github.com/conda-forge/conda-forge.github.io/issues/590#issuecomment-404242397). JavaFX is now available through Maven but those artifacts are not byte code compatible with JavaFX. We are currently limited to JDK8 due to some internal changes to garbage collection in more recent version that break the upstream dependency imglib2-cache for disk-caching of large images (used for example for caching the painting layer). There are plans to address those issues but I am not sure what the exact timeline is. Once we can update to Java 10 (or more recent), we can depend on conda maven and OpenJDK and fetch JavaFX through Maven (having OpenJDK and maven as optional dependencies would be great but I don't know if conda supports that).

**Comment by pgunn** [comment]
Hi,
As far as I can tell, it's only the conda-forge versions of openjdk that ship without JavaFX -- In writing our our local environment instructions, I had to pin openjdk to a version that's in defaults and it all works for us.

**Comment by hanslovsky** [comment]
Unfortunately, the [openjdk version on anaconda](https://anaconda.org/anaconda/openjdk/files?version=8.0.152) is [a little dated](https://wiki.openjdk.java.net/display/jdk8u/JDK+8u152) and I would prefer flexibility for the users to choose their system (or any other) JVM instead. If conda supported optional dependencies, I could add openjdk and maven as optional dependencies but I think [that is not the case (yet)](https://github.com/conda/conda/issues/7502). For now, I will just add a comment to the installation instructions.

**Comment by hanslovsky** [comment]
@pgunn I added installation instructions for openjdk/maven from conda to `README.md` in 8bdc2f4. Does this resolve this issue for you? If not, I will leave this open and we can re-visit once Paintera can use Java > 8 and conda has full support for optional dependencies.

**Comment by cmhulbert** [comment]
Paintera now uses Java 11, and does depend on conda for maven.
