### ISSUE TITLE
Update label-to-block-lookup takes very long

### ISSUE THREAD

**Issue by oflynne** [saalfeldlab/paintera#313]
Committing labels into a source with blocks missing at lower mipmap levels takes forever at the label-to-block-lookup update.  Not sure if this is an artifact of the missing blocks or something else.  Needs to be investigated.

**Comment by cmhulbert** [comment]
I believe the issue here was that when downsampling, the RandomAccessibleInterval over the non-existent blocks still iterates over all entries. This was improved for performance in #546, and in the corresponding imglib2-label-multisets update https://github.com/saalfeldlab/imglib2-label-multisets/pull/34

This instead allows us to skip over cells that are non-existent.
