### ISSUE TITLE
Suggestion: easier clickability for dataset selection?

### ISSUE THREAD

**Issue by GenevieveBuckley** [saalfeldlab/paintera#463]
I find it really difficult to click on the root `/` of an N5 dataset to open it in Paintera (eg: in cases where there is only a single dataset saved in the root location, which happens a fair bit if I generate N5 files from zarr). 

Would it be possible to make the whole line of the dropdown menu clickable, including the whitespace?

If it's easy to implement, it might be a nice way to prevent people from seeing an apparently empty dropdown list, clicking randomly in it but not having anything selected, and assuming Paintera is not capable of reading in the file. It took me a while to figure out I had to position my mouse just so, to be exactly over the thin `/` character in order to be able to load the image data.

**Comment by GenevieveBuckley** [comment]
BTW, "no" is a perfectly adequate answer here - just thought I'd mention it in case it really does turn out to be low hanging fruit that might improve the user experience. I don't know enough about Java to guess how easy or hard these things are.

**Comment by cmhulbert** [comment]
No worries, I think this is a valid suggestion, and should be fairly straight-forward. I'll see if I can address this in the next release. I think your suggestion to make the entire row for each dataset selectable, so you don't only have to click on the (potentially very short) text string, is the right solution. In fact, I suspect that was the original intention, since there are other places where it behaves like this (For example, look at the `Find > Recent` menu when selecting a container). Thanks for reporting this!

**Comment by cmhulbert** [comment]
@GenevieveBuckley this was fixed in the newest update (0.32.0). Feel free to re-open if this isn't resolved.
