### ISSUE TITLE
Cannot open ome.zarr dataset from s3 with credentials

### ISSUE THREAD

**Issue by constantinpape** [saalfeldlab/paintera#540]
Hi paintera team,
we are trying to open a ome.zarr dataset from a bucket protected with credentials from S3. 

The dataset can be opened via `Open N5` with Fiji (if the credentials are set in `~/.aws`):
![image](https://github.com/saalfeldlab/paintera/assets/4263537/bdf875d1-65ce-43c6-9b7a-738a2ef3c83f)
![image](https://github.com/saalfeldlab/paintera/assets/4263537/d04a4600-f855-416e-84c6-6d0cf99800d9)

However, opening in paintera fails:
![image](https://github.com/saalfeldlab/paintera/assets/4263537/f0f06359-1081-4bff-83b4-da77cfef54b7)

It would be great to know how we could open this data in paintera. I have used the latest release (1.3.1) on linux.

@cmhulbert we tried this with Stephan today, and he recommended pinging you about it :). I will send you the credentials for this dataset per mail.

**Comment by cmhulbert** [comment]
@constantinpape thanks for reporting, I'm happy to look into this today, if you are able to share credentials. I'm not sure at first glance what the issues is, but I'll look into it

**Comment by constantinpape** [comment]
Hi Caleb,
I have shared the credentials with you via mails a few days ago already, but will resend them now. Please let me know here if you didn't get the mail.

**Comment by cmhulbert** [comment]
Thank Constantin, I tested with the credentials you provided, and it seems that there were some known bugs that have already been addressed in recent releases of  n5-zarr, n5-aws, and n5-universe. I must have missed them, since Paintera wasn't depending on the newest versions yet. I just released a bugfix version, [Paintera 1.3.2](https://github.com/saalfeldlab/paintera/releases/tag/paintera-1.3.2) that should work.

Please feel free to close the issue if it works for you as well!

**Comment by constantinpape** [comment]
Yes, it's fixed. Thanks a lot for the quick help!
