### ISSUE TITLE
Mesh deadlock

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/paintera#72]
After a few property changes in mesh settings, mesh rendering stalls forever.  No meshes are being generated and all mesh related thread are parked.
![twitter-privacy1](https://user-images.githubusercontent.com/385072/41236165-6bbc93ac-6d5e-11e8-9a1f-f7b39159f515.png)

**Comment by hanslovsky** [comment]
`MeshGeneratorJobManager.ManagmentTask task` is submitted to an `ExecutorService es`. Inside `task` `BlocksForLabelDelgate.apply` is called, which in turn submits requests to look up blocks through a delegate to `es`. When many neurons are clicked (and un-clicked), all threads of `es` are busy with instances of `MeshGeneratorJobManager.ManagmentTask`, which in turn wait for the completion of `BlocksForLabelDelgate.apply`, which in turn submits tasks that can never start (let alone finish) because the queue is already filled up. This is most likely it. I will use [`MoreExecutors.sameThreadExecutor`](https://google.github.io/guava/releases/17.0/api/docs/com/google/common/util/concurrent/MoreExecutors.html#sameThreadExecutor()) to see if that fixes is. If that is the case, we could introduce another `ExecutorService` to deal with this issue if we need to parallelize.

**Comment by hanslovsky** [comment]
@axtimwalde Please try this branch:
https://github.com/saalfeldlab/paintera/tree/mesh-deadlock-part2
